---
# file elkstack.yml
- hosts: all
  become: true
  become_method: sudo

  vars_files:
   - vars/default.yml

  roles:
    - { role: environment }
    - { role: elasticsearch }
    - { role: logstash }
    - { role: nginx-kibana }